clone:
  clone:
    image: 890546402176.dkr.ecr.eu-central-1.amazonaws.com/hubdockercom/plugins/git

pipeline:
  build-push:
    image: golang:1.17.3
    group: QA
    environment:
      - CGO_ENABLED=0
      - GO111MODULE=on
    commands:
      - "go build -v -ldflags \"-X main.version=${DRONE_COMMIT_SHA:0:8}\" -a -tags netgo -o release/linux/amd64/drone-docker ./cmd/drone-docker"
    when:
      event: push

  build-image:
    image: 130607246975.dkr.ecr.eu-central-1.amazonaws.com/drone-plugins/gyg-registry
    pull: true
    privileged: true
    context: . 
    dockerfile: docker/docker/Dockerfile.linux.amd64
    repo: 226747981948.dkr.ecr.eu-central-1.amazonaws.com/service/drone-docker-arm
    tags:
      - latest
      - ${DRONE_BRANCH}
      - v${DRONE_BUILD_NUMBER}.${DRONE_COMMIT_SHA:0:7}
    when:
      event: push
    secrets: [ codeartifact_auth_token ]
    build_args_from_env: [ codeartifact_auth_token ]
