FROM docker:20.10.17-dind

COPY docker/docker/config.json /root/.docker/
COPY docker/docker/daemon.json /etc/docker/

ENV DOCKER_HOST=unix:///var/run/docker.sock


ADD release/linux/amd64/drone-docker /bin/
ENTRYPOINT ["/usr/local/bin/dockerd-entrypoint.sh", "/bin/drone-docker"]
