# escape=`
FROM plugins/docker:windows-1809-amd64

LABEL maintainer="Drone.IO Community <drone-dev@googlegroups.com>" `
  org.label-schema.name="Drone ECR Public" `
  org.label-schema.vendor="Drone.IO Community" `
  org.label-schema.schema-version="1.0"

ADD release/windows/amd64/drone-ecr-public.exe C:/bin/drone-ecr-public.exe
ENTRYPOINT [ "C:\\bin\\drone-ecr-public.exe" ]
